version: '3.1'
services:
  mssql:
    build: .
    image: mssql-windows-express
    hostname: mssqldocker
    environment:
      - 'SA_PASSWORD=P@ssw0rd'
      - attach_dbs=[{'dbName':'DNNDEV','dbFiles':['C:\\SQLData\\DNNDEV.mdf','C:\\SQLData\\DNNDEV_log.ldf']}]
    ports:
     - "1433:1433"